name: Centralized Issue Notification

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour
  workflow_dispatch: # Manual trigger for testing

jobs:
  monitor-issues:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch All Repositories
        id: fetch_repos
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          ORG_NAME="your-organization-name" # Replace with your organization or username
          curl -H "Authorization: token $PAT" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/orgs/$ORG_NAME/repos?per_page=100" > repos.json

          # Extract repository names and save them as a JSON array
          jq -r '.[].full_name' repos.json > repo_list.txt
          echo "REPOS=$(cat repo_list.txt | paste -sd,)" >> $GITHUB_ENV

      - name: Process Issues for All Repositories
        env:
          REPOS: ${{ env.REPOS }}
          PAT: ${{ secrets.PAT }}
        run: |
          IFS=',' read -ra REPO_ARRAY <<< "$REPOS"
          for REPO in "${REPO_ARRAY[@]}"; do
            echo "Fetching issues for $REPO..."
            curl -H "Authorization: token $PAT" \
                 -H "Accept: application/vnd.github.v3+json" \
                 "https://api.github.com/repos/$REPO/issues?state=open" > "$REPO-issues.json"

            # Process issues and send email notifications (logic can be added here)
          done
