name: Issue Notification for Non-Leidos Employees

on: 
  issues: 
    types: [opened]
env:
  ACTIONS_STEP_DEBUG: true
  
jobs: 
  notify: 
    runs-on: ubuntu-latest 
    steps: 
    - name: Check if user is a Leidos employee 
      id: check_leidos 
      uses: actions/github-script@v6 
      with: 
        script: | 
          const issueBody = context.payload.issue.body; 
          const isLeidosEmployee = issueBody.includes('Are you Saxton Lab/Leidos employee?') && 
                                    issueBody.includes('No'); 
          core.setOutput('notify', isLeidosEmployee ? 'true' : 'false');
    - name: Send Email Notification 
      if: steps.check_leidos.outputs.notify == 'true' 
      uses: dawidd6/action-send-mail@v3 
      with: 
       server_address: smtp.gmail.com # Replace with your SMTP server 
       server_port: 587 # Replace with your SMTP server port 
       username: ${{ secrets.SMTP_USERNAME }} # Store SMTP credentials in GitHub secrets 
       password: ${{ secrets.SMTP_PASSWORD }} 
       subject: "New Issue from Non-Leidos Employee" 
       body: | 
         A new issue was created by a non-Leidos employee: 
         Title: ${{ github.event.issue.title }} 
         URL: ${{ github.event.issue.html_url }} 
         Description: ${{ github.event.issue.body }} 
       to: devulapallitanuj@gmail.com
       from: ${{ secrets.SMTP_USERNAME }} # Replace with the email address you want to use
       
